# Hello App Deployment
# A simple Python Flask application that connects to PostgreSQL and makes external API calls
#
# Key features:
# - Deployed in 'demo' namespace with Istio ambient mode enabled
# - Uses dedicated ServiceAccount for Istio identity (SPIFFE ID)
# - Connects to postgres database
# - Makes external HTTPS requests to api.github.com
# - Health probes for liveness and readiness
#
# In Istio ambient mode:
# - All traffic is transparently intercepted and routed through ztunnel
# - mTLS is enforced between workloads via PeerAuthentication policy
# - Identity is based on Kubernetes ServiceAccount (SPIFFE format)
# - No sidecar injection required - ztunnel handles L4 proxy functionality

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-app
  namespace: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
        version: v1
    spec:
      serviceAccountName: hello-app
      containers:
        - name: hello-app
          image: hello-db-app:latest
          imagePullPolicy: Never # Using local image built for kind
          ports:
            - containerPort: 8000
          # Health probes for Kubernetes orchestration
          # Note: In ambient mode, kubelet probes bypass ztunnel and appear as 'world' entity in Cilium policies
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: hello
            - name: DB_PASSWORD
              value: hello
            - name: DB_NAME
              value: hellodb
---
# Service for hello-app
# Provides stable DNS name and ClusterIP for the hello-app workload
# Traffic to this service is subject to Istio AuthorizationPolicy and Cilium NetworkPolicy
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: demo
spec:
  selector:
    app: hello-app
  ports:
    - name: http # Named port 'http' - required for Istio protocol detection
      port: 8000
      targetPort: 8000
