apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-app
  namespace: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
        version: v1
    spec:
      serviceAccountName: hello-app
      containers:
        - name: hello-app
          image: hello-db-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: hello
            - name: DB_PASSWORD
              value: hello
            - name: DB_NAME
              value: hellodb
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: demo
spec:
  selector:
    app: hello-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
